export default [
  'Al Pacino',
  'Andy Griffith',
  'Anthony Hopkins',
  'Audrey Hepburn',
  'Betty White',
  'Bill Murray',
  'Bruce Lee',
  'Bruce Willis',
  'Carol Burnett',
  'Christopher Reeve',
  'Clint Eastwood',
  'Danny DeVito',
  'Denzel Washington',
  'Dick Van Dyke',
  'Drew Barrymore',
  'Dwayne Johnson',
  'Eddie Murphy',
  'Gene Wilder',
  'Halle Berry',
  'Harrison Ford',
  'Hugh Jackman',
  'Jack Nicholson',
  'Jackie Chan',
  'James Earl Jones',
  'Jamie Lee Curtis',
  'Jennifer Aniston',
  'Julia Roberts',
  'Julie Andrews',
  'Keanu Reeves',
  'Kurt Russell',
  'Liam Neeson',
  'Lucille Ball',
  'Marilyn Monroe',
  'Michael J. Fox',
  'Morgan Freeman',
  'Patrick Swayze',
  'Paul Newman',
  'Reese Witherspoon',
  'Robert Downey Jr.',
  'Robin Williams',
  'Sally Field',
  'Samuel L. Jackson',
  'Sandra Bullock',
  'Sean Connery',
  'Shirley Temple',
  'Steve Martin',
  'Tim Allen',
  'Tom Hanks',
  'Tommy Lee Jones',
  'Will Smith'
];
